version: '3.4'

services:
  appdb:
    container_name: app-db
    image: mcr.microsoft.com/azure-sql-edge:latest
    #  image: mcr.microsoft.com/mssql/server:2019-latest
    #ports:
     # - 8002:1433
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - AnimeBookshelfapp

  animebookshelf:
    container_name: AnimeBookshelf
    image: ${DOCKER_REGISTRY-}animebookshelf
    build:
      context: .
      dockerfile: AnimeBookshelf/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - appdb
    environment:
      - DB_HOST=appdb
      - DB_NAME=AnimeBooksshelf
      - DB_SA_PASSWORD=password@12345#
    networks:
      - AnimeBookshelfapp

networks:
  AnimeBookshelfapp:
    driver: bridge

